header_items:
  type: list
  default: "This space is intentionally left empty|This space will be different soon"
  description: "Allows for multiple Global Banner messages that rotate on page refreshes."
